[package]
name = "food"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "app"
path = "src/main.rs"

[workspace]
members = [".", "./crates/migrations", "./crates/entities", "./crates/database"]

[dependencies]
sea-orm = { version = "^0.12.0", features = ["sqlx-postgres", "runtime-async-std-native-tls", "macros"] }
sea-orm-migration = { version = "^0.12.0" }
futures = "0.3.28"
migrations = { path = "./crates/migrations" }
database = { path = "./crates/database" }
uuid = { version = "1.6.1", features = ["v4"] }
chrono = "0.4.31"
