//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

pub mod prelude;

pub mod categories;
pub mod ingredients;
pub mod pantry_items;
pub mod recipe_categories;
pub mod recipe_ingredients;
pub mod recipes;
pub mod users;
