name: Rust CI

on:
  push:
  pull_request:
    branches: []

env:
  RUST_CHANNEL: 1.75.0-x86_64-unknown-linux-gnu
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust toolchain
        run: |
          rustup update --no-self-update ${{ env.RUST_CHANNEL }}
          rustup component add --toolchain ${{ env.RUST_CHANNEL }} rustfmt rust-src
          rustup default ${{ env.RUST_CHANNEL }}
      - run: cargo +${{ env.RUST_CHANNEL }} install --all-features --locked --profile release --path ${{ github.GITHUB_WORKSPACE }}
      - run: cargo +${{ env.RUST_CHANNEL }} build --workspace --all-targets --all-features --profile dev
      - uses: actions/upload-artifact@master
        with:
          name: build
          path: dist
  # publish-image:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   if: github.ref == 'refs/heads/main'
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/download-artifact@master
  #       with:
  #         name: build
  #         path: dist
  #     - name: Log in to the Container registry
  #       uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
  #       with:
  #         registry: ${{ env.REGISTRY }}
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.PACKAGES_TOKEN }}
  #     - run: docker build -t fridge-tracker-frontend .
  #     - run: |-
  #         TAG="$(cat package.json | jq -r '.version')"
  #         docker tag fridge-tracker-frontend ${REGISTRY}/${GITHUB_ACTOR}/fridge-tracker-frontend:${TAG}
  #         docker push ${REGISTRY}/${GITHUB_ACTOR}/fridge-tracker-frontend:${TAG}
